Repository CS2103-AY1819S1-T09-4/main, pull requests merged in 2018-10, with the labels that each got.

#28 Update author names for Reposense
  .gitignore
  _reposense/config.json
  src/main/java/seedu/address/model/carpark/Address.java
  src/main/java/seedu/address/model/carpark/Carpark.java
  src/main/java/seedu/address/model/carpark/CarparkNumber.java
  src/main/java/seedu/address/model/carpark/CarparkType.java
  src/main/java/seedu/address/model/carpark/Coordinate.java
  src/main/java/seedu/address/model/carpark/FreeParking.java
  src/main/java/seedu/address/model/carpark/LotsAvailable.java
  src/main/java/seedu/address/model/carpark/NightParking.java
  src/main/java/seedu/address/model/carpark/ShortTerm.java
  src/main/java/seedu/address/model/carpark/TotalLots.java
  src/main/java/seedu/address/model/carpark/TypeOfParking.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/Storage.java
Labels: priority.High

#34 Updating HTML and Userdocs
  docs/DummySearchPage.html
  docs/UserGuide.adoc
  docs/images/Ui2.pdn
  docs/images/Ui2.png
  docs/images/findafter.pdn
  docs/images/findafter.png
  docs/images/findbefore.pdn
  docs/images/findbefore.png
  docs/images/listafter.png
  docs/images/select.png
  docs/images/selectafter.pdn
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/carpark/CarparkContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/CarparkTest.java
Labels: priority.High, severity.High, v1.2

#37 Update UGDG. Also rename notify to query command.
  docs/DeveloperGuide.adoc
  docs/DummySearchPage.html
  docs/UserGuide.adoc
  docs/images/query.png
  docs/images/zy_seq.png
  src/main/java/seedu/address/commons/util/GsonUtil.java
  src/main/java/seedu/address/logic/commands/QueryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.High, type.Task, v1.2

#36 Fix test cases, added back xml file check cases, started updating DG …
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/data/ConfigUtilTest/EmptyConfig.json
  src/test/data/ConfigUtilTest/ExtraValuesConfig.json
  src/test/data/ConfigUtilTest/NotJsonFormatConfig.json
  src/test/data/ConfigUtilTest/TypicalConfig.json
  src/test/data/JsonUserPrefsStorageTest/EmptyUserPrefs.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/NotJsonFormatUserPrefs.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/data/XmlAddressBookStorageTest/NotXmlFormatAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/empty.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/tempAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/CarparkContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/CarparkTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalCarparks.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: help wanted, priority.Medium, severity.Medium, v1.2

#60 Merging documentation and previous PR
  docs/DeveloperGuide.adoc
  docs/images/actdiagram-find.png
  docs/images/seqdiagram-find.png
Labels: priority.High, v1.2

#63 Change command summary in UG to table format.
  docs/UserGuide.adoc
Labels: documentation, priority.Medium

#64 Updates To UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: documentation, priority.Medium

#65 Update DG to a more standardized format.(Section 2 and 3.5)
  docs/DeveloperGuide.adoc
Labels: documentation, priority.Medium

#67 Further edits to the Developer Guide
  docs/DeveloperGuide.adoc
Labels: documentation, priority.Medium, v1.3

#70 Update correct activity diagram for Alias commands, according to Tutor's comment.
  docs/DeveloperGuide.adoc
  docs/images/ActivityDiagram-Alias.png
  docs/images/AliasActivityDiagram.jpg
Labels: documentation, severity.Low

#68 Update to DG sections 2.8 and 2.9 and Filter function + Clean up DG
  docs/DeveloperGuide.adoc
  docs/images/ActivityDiagram.png
  docs/images/SequenceDiagram.png
Labels: documentation, priority.High, v1.3

#71 Change Alias mechanism in DG to Abbreviation mechanism and update con…
  docs/DeveloperGuide.adoc
  docs/images/ActivityDiagram-Alias.png
Labels: documentation

#74 Updated userdocs
  docs/UserGuide.adoc
Labels: documentation

#76 Cleaned up docs and updated more details
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: documentation, priority.Medium, type.Story, v1.2

#77 Update to v1.2.1
  src/main/java/seedu/parking/MainApp.java
  src/main/java/seedu/parking/logic/parser/ParserUtil.java
  src/main/java/seedu/parking/model/VersionedCarparkFinder.java
  src/main/java/seedu/parking/model/carpark/Carpark.java
  src/main/java/seedu/parking/model/carpark/CarparkNumber.java
  src/main/java/seedu/parking/model/carpark/Coordinate.java
  src/main/java/seedu/parking/model/carpark/LotsAvailable.java
  src/main/java/seedu/parking/storage/XmlAdaptedCarpark.java
  src/test/java/seedu/parking/model/VersionedCarparkFinderTest.java
  src/test/java/seedu/parking/model/carpark/AddressTest.java
  src/test/java/seedu/parking/model/carpark/CarparkContainsKeywordsPredicateTest.java
  src/test/java/seedu/parking/model/carpark/CarparkNumberTest.java
  src/test/java/seedu/parking/model/carpark/CarparkTest.java
  src/test/java/seedu/parking/model/carpark/CarparkTypeTest.java
  src/test/java/seedu/parking/model/carpark/CoordinateTest.java
  src/test/java/seedu/parking/model/carpark/FreeParkingTest.java
  src/test/java/seedu/parking/model/carpark/LotsAvailableTest.java
  src/test/java/seedu/parking/model/carpark/NameTest.java
  src/test/java/seedu/parking/model/carpark/NightParkingTest.java
  src/test/java/seedu/parking/model/carpark/PhoneTest.java
  src/test/java/seedu/parking/model/carpark/ShortTermTest.java
  src/test/java/seedu/parking/model/carpark/TotalLotsTest.java
  src/test/java/seedu/parking/model/carpark/TypeOfParkingTest.java
Labels: documentation, priority.High, v1.3

#75 Added autocomplete mechanism on complicated commands
  docs/images/ActivityDiagram-alias.png
  src/main/java/seedu/parking/logic/commands/FilterCommand.java
  src/main/java/seedu/parking/logic/commands/FindCommand.java
  src/main/java/seedu/parking/logic/commands/SelectCommand.java
  src/main/java/seedu/parking/logic/parser/CliSyntax.java
  src/main/java/seedu/parking/ui/CommandBox.java
Labels: enhancement, priority.Medium, v1.3

#78 Edited Sequence diagram
  docs/DeveloperGuide.adoc
  docs/images/SequenceDiagram-filter.png
Labels: documentation, priority.Medium, v1.3

#81 UG and DG completed for auto-complete mechanism.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ActivityDiagram-autocompletion.png
  docs/images/screenshot-fi.png
  docs/images/screenshot-fiFirstArgSelected.png
  docs/images/screenshot-fiSecondArgSelected.png
Labels: documentation, priority.Medium, type.Story, v1.3

#82 Updates on Notify and in general
  README.adoc
  _reposense/config.json
  docs/AboutUs.adoc
  docs/team/zhuanyu.adoc
  src/main/java/seedu/parking/commons/events/ui/NotifyCarparkRequestEvent.java
  src/main/java/seedu/parking/commons/util/GsonUtil.java
  src/main/java/seedu/parking/logic/commands/ClearCommand.java
  src/main/java/seedu/parking/logic/commands/ListCommand.java
  src/main/java/seedu/parking/logic/commands/NotifyCommand.java
  src/main/java/seedu/parking/logic/commands/QueryCommand.java
  src/main/java/seedu/parking/logic/commands/SelectCommand.java
  src/main/java/seedu/parking/logic/parser/CarparkFinderParser.java
  src/main/java/seedu/parking/logic/parser/NotifyCommandParser.java
  src/main/java/seedu/parking/logic/parser/ParserUtil.java
  src/main/java/seedu/parking/model/Model.java
  src/main/java/seedu/parking/model/ModelManager.java
  src/main/java/seedu/parking/ui/CarparkListPanel.java
  src/test/java/seedu/parking/logic/LogicManagerTest.java
  src/test/java/seedu/parking/logic/commands/ClearCommandTest.java
  src/test/java/seedu/parking/logic/commands/ListCommandTest.java
  src/test/java/seedu/parking/logic/parser/CarparkFinderParserTest.java
  src/test/java/seedu/parking/logic/parser/NotifyCommandParserTest.java
  src/test/java/seedu/parking/logic/parser/ParserUtilTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: documentation, priority.High, v1.3

#80 Improved Filter command
  src/main/java/seedu/parking/logic/commands/FilterCommand.java
  src/main/java/seedu/parking/logic/commands/FindCommand.java
  src/main/java/seedu/parking/model/Model.java
  src/main/java/seedu/parking/model/ModelManager.java
  src/main/java/seedu/parking/model/carpark/CarparkContainsKeywordsPredicate.java
  src/main/java/seedu/parking/model/carpark/CarparkFilteringPredicate.java
  src/main/java/seedu/parking/model/carpark/CarparkHasFreeParkingPredicate.java
  src/main/java/seedu/parking/model/carpark/CarparkHasNightParkingPredicate.java
  src/main/java/seedu/parking/model/carpark/CarparkIsOfTypePredicate.java
Labels: priority.High, v1.3

#83 Postal Code and documentation
  docs/DummySearchPage.html
  docs/styles.css
  docs/team/keith.adoc
  postalcodeData.txt
  src/main/java/seedu/parking/MainApp.java
  src/main/java/seedu/parking/commons/util/CarparkJson.java
  src/main/java/seedu/parking/commons/util/GeocodeInfoJson.java
  src/main/java/seedu/parking/commons/util/GsonUtil.java
  src/main/java/seedu/parking/logic/commands/NotifyCommand.java
  src/main/java/seedu/parking/logic/commands/QueryCommand.java
  src/main/java/seedu/parking/model/carpark/Carpark.java
  src/main/java/seedu/parking/model/carpark/PostalCode.java
  src/main/java/seedu/parking/model/util/SampleDataUtil.java
  src/main/java/seedu/parking/storage/XmlAdaptedCarpark.java
  src/main/java/seedu/parking/ui/CarparkCard.java
  src/main/resources/view/CarparkListCard.fxml
  src/test/data/XmlCarparkFinderStorageTest/invalidAndValidCarparkCarparkFinder.xml
  src/test/data/XmlCarparkFinderStorageTest/invalidCarparkCarparkFinder.xml
  src/test/data/XmlSerializableCarparkFinderTest/duplicateCarparkCarparkFinder.xml
  src/test/data/XmlSerializableCarparkFinderTest/invalidCarparkCarparkFinder.xml
  src/test/data/XmlSerializableCarparkFinderTest/typicalCarparksCarparkFinder.xml
  src/test/data/XmlUtilTest/invalidCarparkField.xml
  src/test/data/XmlUtilTest/missingCarparkField.xml
  src/test/data/XmlUtilTest/validCarpark.xml
  src/test/data/XmlUtilTest/validCarparkFinder.xml
  src/test/java/seedu/parking/commons/util/GsonUtilTest.java
  src/test/java/seedu/parking/commons/util/JsonUtilTest.java
  src/test/java/seedu/parking/commons/util/XmlUtilTest.java
  src/test/java/seedu/parking/testutil/CarparkBuilder.java
  src/test/java/seedu/parking/testutil/TypicalCarparks.java
  src/test/java/seedu/parking/ui/CarparkListPanelTest.java
Labels: documentation, priority.Medium, status.Ongoing, v1.3

#84 Update DG to meet milestone 1.3
  docs/DeveloperGuide.adoc
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation, severity.High, status.Ongoing, v1.3

#85 Updated developer guide formatting
  docs/DeveloperGuide.adoc
  docs/DummySearchPage.html
  docs/images/General new command.png
  docs/images/Sequence Diagram - Undo.png
  docs/images/Sequence diagram - Find Carpark Event Handling.png
  docs/images/Sequence diagram - Find Carpark.png
  docs/images/UndoRedoActivityDiagramNew1.png
  docs/images/UndoRedoActivityDiagramNew2.png
  docs/images/UndoRedoActivityDiagramNew3.png
  docs/images/UndoRedoActivityDiagramNew4.png
  docs/images/UndoRedoActivityDiagramNew5.png
  docs/images/UndoRedoActivityDiagramNew6.png
  docs/styles.css
Labels: documentation, priority.High, v1.3

#87 Update UG to make it easier to comprehend, especially Quick Start Section.
  docs/UserGuide.adoc
  docs/images/quickstart-GUI.png
Labels: documentation, priority.Medium, v1.3

#90 Many new stuffs... including update of UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CarparkFilteringPredicate_code_snippet.PNG
  src/main/java/seedu/parking/commons/core/Messages.java
  src/main/java/seedu/parking/logic/commands/CalculateCommand.java
  src/main/java/seedu/parking/logic/commands/FilterCommand.java
  src/main/java/seedu/parking/logic/commands/FindCommand.java
  src/main/java/seedu/parking/logic/parser/CalculateCommandParser.java
  src/main/java/seedu/parking/logic/parser/CarparkFinderParser.java
  src/main/java/seedu/parking/logic/parser/CarparkTypeParameter.java
  src/main/java/seedu/parking/logic/parser/FilterCommandParser.java
  src/main/java/seedu/parking/logic/parser/FreeParkingParameter.java
  src/main/java/seedu/parking/logic/parser/ParkingSystemTypeParameter.java
  src/main/java/seedu/parking/model/Model.java
  src/main/java/seedu/parking/model/ModelManager.java
  src/main/java/seedu/parking/model/carpark/CarparkContainsKeywordsPredicate.java
  src/main/java/seedu/parking/model/carpark/CarparkFilteringPredicate.java
  src/main/java/seedu/parking/model/carpark/CarparkIsOfNumberPredicate.java
  src/main/java/seedu/parking/model/carpark/CarparkNumber.java
  src/main/java/seedu/parking/model/carpark/CarparkType.java
  src/main/java/seedu/parking/model/carpark/FreeParking.java
  src/main/java/seedu/parking/model/carpark/LotsAvailable.java
  src/main/java/seedu/parking/model/carpark/NightParking.java
  src/main/java/seedu/parking/model/carpark/ShortTerm.java
  src/main/java/seedu/parking/model/carpark/TypeOfParking.java
Labels: priority.High

#91 Fix missing images in AboutUs.adoc
  docs/AboutUs.adoc
  docs/images/alvin.png
  docs/images/delong.jpg
  docs/images/keith.png
  docs/images/yurou.jpg
Labels: bug, documentation, severity.High, v1.3

#92 v1.3
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/SequenceDiagram-filter.png
  docs/images/Ui.png
  docs/images/Ui2.png
  docs/images/query.png
  docs/images/seqdiagram-find.png
  docs/images/zy_after_query.png
  docs/images/zy_arrow.png
  docs/images/zy_before_query.png
  docs/images/zy_during_query.png
  docs/images/zy_notify_after.png
  docs/images/zy_notify_invalid.png
  docs/images/zy_notify_off.png
  docs/images/zy_notify_select.png
  docs/images/zy_select_notify.png
  docs/images/zy_seq.png
  src/main/java/seedu/parking/commons/util/GsonUtil.java
Labels: documentation, priority.High, v1.3

#93 Updates to fix v1.3
  src/main/java/seedu/parking/commons/core/Config.java
  src/main/java/seedu/parking/commons/util/GsonUtil.java
  src/main/java/seedu/parking/model/UserPrefs.java
  src/test/java/seedu/parking/commons/core/ConfigTest.java
Labels: documentation, priority.High, v1.3
