Repository CS2103-AY1819S1-T09-4/main, pull requests merged in 2018-11, with the labels that each got.

#97 Update PPP up to v1.3
  docs/team/delong.adoc
Labels: documentation, priority.High

#98 Merging Delong and Yurou PPP.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/keith.adoc
Labels: documentation, priority.High

#101 Trying to see if parseInt fixes the cutting of markers
  docs/DummySearchPage.html
  docs/team/zhuanyu.adoc
Labels: documentation

#103 Add markerCluster to google map
  docs/DummySearchPage.html
  src/main/resources/script/svy21.js
Labels: enhancement, priority.Medium

#102 Updated documentation and UI
  docs/DeveloperGuide.adoc
  docs/DummySearchPage.html
  docs/UserGuide.adoc
  docs/team/keith.adoc
  docs/team/keithstyles.css
  src/main/java/seedu/parking/commons/events/ui/CarparkPanelSelectionChangedEvent.java
  src/main/java/seedu/parking/commons/events/ui/FilterResultChangedEvent.java
  src/main/java/seedu/parking/commons/events/ui/FindResultChangedEvent.java
  src/main/java/seedu/parking/logic/commands/FilterCommand.java
  src/main/java/seedu/parking/logic/commands/FindCommand.java
  src/main/java/seedu/parking/ui/BrowserPanel.java
  src/main/resources/data/postalcodeData.txt
  src/test/java/seedu/parking/ui/BrowserPanelTest.java
  src/test/java/systemtests/CarparkFinderSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: documentation, enhancement, priority.Medium

#113 v1.3.1 Update PPP for all
  .travis.yml
  build.gradle
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/DummySearchPage.html
  docs/LearningOutcomes.adoc
  docs/MainPage.html
  docs/UserGuide.adoc
  docs/UsingAppVeyor.adoc
  docs/UsingCheckstyle.adoc
  docs/UsingCoveralls.adoc
  docs/UsingGradle.adoc
  docs/UsingNetlify.adoc
  docs/UsingTravis.adoc
  docs/script/markerclusterer.js
  docs/script/svy21.js
  docs/stylesheets/default.css
  docs/stylesheets/gh-pages.css
  docs/stylesheets/keith.css
  docs/stylesheets/zhuanyu.css
  docs/team/alvin.adoc
  docs/team/delong.adoc
  docs/team/keith.adoc
  docs/team/yurou.adoc
  docs/team/zhuanyu.adoc
  src/main/java/seedu/parking/commons/events/ui/FilterResultChangedEvent.java
  src/main/java/seedu/parking/commons/events/ui/FindResultChangedEvent.java
  src/main/java/seedu/parking/commons/util/GsonUtil.java
  src/main/java/seedu/parking/ui/BrowserPanel.java
  src/main/java/seedu/parking/ui/MainWindow.java
  src/main/java/seedu/parking/ui/StatusBarFooter.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/parking/ui/BrowserPanelTest.java
  src/test/java/systemtests/CarparkFinderSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: documentation, priority.High, v1.4

#118 change markers path location
  docs/MainPage.html
  docs/images/m1.png
  docs/images/m2.png
  docs/images/m3.png
  docs/images/m4.png
  docs/images/m5.png
  src/main/resources/images/m1.png
  src/main/resources/images/m2.png
  src/main/resources/images/m3.png
  src/main/resources/images/m4.png
  src/main/resources/images/m5.png
Labels: v1.4

#119 v1.3.1
  docs/MainPage.html
  src/main/java/seedu/parking/MainApp.java
Labels: v1.4

#120 Updating documentation for new UI
  docs/DeveloperGuide.adoc
  docs/MainPage.html
  docs/UserGuide.adoc
  docs/images/UIstep1.png
  docs/images/UIstep3.png
  docs/images/Ui.png
  docs/images/Uistep2.png
  docs/images/afterhistory.png
  docs/images/afterlist.png
  docs/images/beforeclear.png
  docs/images/beforehistory.png
  docs/images/beforelist.png
  docs/images/findafter.png
  docs/images/findbefore.png
  docs/images/select.png
  docs/images/selectafter.pdn
  docs/images/selectafter.png
  docs/index.adoc
  docs/stylesheets/keith.css
  docs/team/keith.adoc
  src/main/java/seedu/parking/commons/events/ui/ClearResultChangedEvent.java
  src/main/java/seedu/parking/logic/commands/ClearCommand.java
  src/main/java/seedu/parking/ui/BrowserPanel.java
  src/test/java/systemtests/ClearCommandSystemTest.java
Labels: documentation, enhancement, priority.High, v1.4

#122 Update the colour of the application
  docs/images/m1.png
  docs/images/m2.png
  docs/images/m3.png
  docs/images/m4.png
  docs/images/m5.png
  docs/team/alvinnyk.adoc
  docs/team/dlworldpeace.adoc
  docs/team/lexzt.adoc
  docs/team/yuroutang.adoc
  src/main/java/seedu/parking/commons/core/Config.java
  src/main/java/seedu/parking/model/UserPrefs.java
  src/main/java/seedu/parking/model/util/SampleDataUtil.java
  src/main/java/seedu/parking/ui/CarparkCard.java
  src/main/java/seedu/parking/ui/CarparkListPanel.java
  src/main/java/seedu/parking/ui/CommandBox.java
  src/main/java/seedu/parking/ui/UiManager.java
  src/main/resources/images/m3.png
  src/main/resources/view/AppTheme.css
  src/main/resources/view/CarparkListCard.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/default.html
  src/test/java/seedu/parking/commons/core/ConfigTest.java
  src/test/java/seedu/parking/ui/testutil/UiPartRule.java
Labels: enhancement

#123 Update PPP and AboutUs. Change Abbreviation mechanism to fit more cases.
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/stylesheets/delong.css
  docs/team/dlworldpeace.adoc
  src/main/java/seedu/parking/commons/core/Messages.java
  src/main/java/seedu/parking/logic/commands/CalculateCommand.java
  src/main/java/seedu/parking/logic/commands/ExitCommand.java
  src/main/java/seedu/parking/logic/commands/FilterCommand.java
  src/main/java/seedu/parking/logic/commands/FindCommand.java
  src/main/java/seedu/parking/logic/commands/HelpCommand.java
  src/main/java/seedu/parking/logic/commands/ListCommand.java
  src/main/java/seedu/parking/logic/commands/NotifyCommand.java
  src/main/java/seedu/parking/logic/commands/QueryCommand.java
  src/main/java/seedu/parking/logic/commands/SelectCommand.java
  src/main/java/seedu/parking/logic/parser/CarparkFinderParser.java
  src/main/java/seedu/parking/ui/CommandBox.java
  src/test/java/seedu/parking/logic/parser/CarparkFinderParserTest.java
Labels: enhancement, priority.Medium, v1.4

#127 Update UG for new abbr mechanism. Improve test cases for CarparkFinderParser.
  docs/UserGuide.adoc
  src/main/java/seedu/parking/logic/commands/CalculateCommand.java
  src/main/java/seedu/parking/logic/commands/FilterCommand.java
  src/test/java/seedu/parking/logic/parser/CarparkFinderParserTest.java
Labels: enhancement, priority.High, v1.4

#131 New mechanism for auto-complete.
  src/main/java/seedu/parking/commons/core/Messages.java
  src/main/java/seedu/parking/logic/commands/CalculateCommand.java
  src/main/java/seedu/parking/logic/commands/FilterCommand.java
  src/main/java/seedu/parking/logic/parser/CliSyntax.java
  src/main/java/seedu/parking/ui/CommandBox.java
Labels: bug

#135 Test Cases for Filter and Calculate
  docs/UserGuide.adoc
  docs/images/calculate_screenshot.png
  docs/images/filter_screenshot.png
  src/main/java/seedu/parking/commons/core/Messages.java
  src/main/java/seedu/parking/logic/commands/CalculateCommand.java
  src/main/java/seedu/parking/logic/commands/FilterCommand.java
  src/main/java/seedu/parking/logic/parser/CalculateCommandParser.java
  src/main/java/seedu/parking/logic/parser/FilterCommandParser.java
  src/main/java/seedu/parking/model/carpark/CarparkFilteringPredicate.java
  src/test/java/seedu/parking/logic/commands/CalculateCommandTest.java
  src/test/java/seedu/parking/logic/commands/FilterCommandTest.java
  src/test/java/seedu/parking/logic/parser/CalculateCommandParserTest.java
  src/test/java/seedu/parking/logic/parser/CarparkFinderParserTest.java
  src/test/java/seedu/parking/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/parking/model/carpark/CarparkFilteringPredicateTest.java
  src/test/java/seedu/parking/model/carpark/CarparkIsOfNumberPredicateTest.java
Labels: documentation

#137 Fix notify bug where cannot change selection[Don't accept testing travis]
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/UIstep1.png
  docs/images/UIstep3.png
  docs/images/UiS1.png
  docs/images/UiS2.png
  docs/images/UiS3.png
  docs/images/Uistep2.png
  docs/team/zhuanyu.adoc
  src/main/java/seedu/parking/commons/util/GsonUtil.java
  src/main/java/seedu/parking/logic/NotifyTimeTask.java
  src/main/java/seedu/parking/logic/commands/NotifyCommand.java
  src/main/java/seedu/parking/model/ModelManager.java
  src/main/java/seedu/parking/ui/CarparkListPanel.java
  src/main/resources/view/postalcodeData.txt
  src/test/java/seedu/parking/commons/util/GsonUtilTest.java
  src/test/java/seedu/parking/commons/util/StringUtilTest.java
Labels: documentation, status.Ongoing

#139 Updating documentation and PPP
  docs/DeveloperGuide.adoc
  docs/MainPage.html
  docs/UserGuide.adoc
  docs/images/actdiagram-findresize.png
  docs/stylesheets/keith.css
  docs/team/lexzt.adoc
Labels: documentation, priority.High

#136 Bug Fix and and edits to PPP
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/images/calculate_screenshot.png
  docs/images/filter_screenshot.png
  docs/team/yuroutang.adoc
  src/main/java/seedu/parking/commons/core/Messages.java
  src/main/java/seedu/parking/model/carpark/CarparkFilteringPredicate.java
Labels: documentation, severity.High

#133 Refine auto-complete feature to be more bug-free.
  docs/UserGuide.adoc
  src/main/java/seedu/parking/commons/core/Messages.java
  src/main/java/seedu/parking/logic/commands/CalculateCommand.java
  src/main/java/seedu/parking/logic/commands/FilterCommand.java
  src/main/java/seedu/parking/ui/CommandBox.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/parking/ui/CommandBoxTest.java
Labels: status.Ongoing, type.Bug, v1.4
